import type { Entry } from './entry';
import type { Lang, SymptomTag } from '../i18n/types';
import { avgOf } from './domain';
import { meta, tagLabel } from '../i18n/meta';

function downloadFile(filename: string, content: BlobPart, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function exportEntriesJson(entries: Entry[]) {
  const stamp = new Date().toISOString().slice(0, 10);
  downloadFile(`kantu-registros-${stamp}.json`, JSON.stringify(entries, null, 2), 'application/json');
}

const SUMMARY_TYPES = ['bp', 'glucose', 'hr', 'weight', 'mood', 'focus'] as const;
const PAGE_RIGHT = 548;
const MARGIN_X = 48;

async function buildSummaryPdf(lang: Lang, entries: Entry[], periodLabel: string): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const p = (a: string, b: string) => (lang === 'es' ? a : b);
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  let y = 64;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(33, 31, 40);
  doc.text('Kantu', MARGIN_X, y);
  y += 26;
  doc.setFontSize(14);
  doc.text(p('Resumen para el doctor', 'Summary for the doctor'), MARGIN_X, y);
  y += 22;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(111, 106, 125);
  doc.text(p('Periodo', 'Period') + ': ' + periodLabel, MARGIN_X, y);
  y += 28;

  doc.setDrawColor(33, 31, 40);
  doc.setLineWidth(1);
  doc.line(MARGIN_X, y, PAGE_RIGHT, y);
  y += 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(33, 31, 40);
  doc.text(p('PROMEDIOS', 'AVERAGES'), MARGIN_X, y);
  y += 18;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  SUMMARY_TYPES.forEach((type) => {
    doc.text(meta(lang, type).full, MARGIN_X, y);
    doc.text(avgOf(lang, entries, type) || '—', PAGE_RIGHT, y, { align: 'right' });
    y += 20;
  });

  y += 12;
  doc.setDrawColor(33, 31, 40);
  doc.line(MARGIN_X, y, PAGE_RIGHT, y);
  y += 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(p('SÍNTOMAS ANOTADOS', 'SYMPTOMS LOGGED'), MARGIN_X, y);
  y += 18;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  const counts: Partial<Record<SymptomTag, number>> = {};
  entries.filter((e) => e.type === 'symptom').forEach((e) => (e.tags || []).forEach((tg) => (counts[tg] = (counts[tg] || 0) + 1)));
  const keys = Object.keys(counts) as SymptomTag[];
  if (!keys.length) {
    doc.text('- ' + p('Ninguno anotado', 'None logged'), MARGIN_X, y);
    y += 20;
  } else {
    keys.forEach((k) => {
      doc.text('- ' + tagLabel(lang, k) + ' × ' + counts[k], MARGIN_X, y);
      y += 20;
    });
  }

  y += 20;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(111, 106, 125);
  const footer = p(
    'Generado por Kantu — no sustituye a tu médica ni te da un diagnóstico.',
    'Generated by Kantu — it does not replace your doctor and gives no diagnosis.',
  );
  doc.text(doc.splitTextToSize(footer, PAGE_RIGHT - MARGIN_X), MARGIN_X, y);

  return doc.output('blob');
}

export type SummaryShareOutcome = 'shared' | 'downloaded' | 'cancelled';

/** Builds the doctor summary as a PDF and, on devices that support it, opens the
 * native share sheet (email, WhatsApp, etc.) instead of a silent file download. */
export async function shareDoctorSummary(lang: Lang, entries: Entry[], periodLabel: string): Promise<SummaryShareOutcome> {
  const p = (a: string, b: string) => (lang === 'es' ? a : b);
  const blob = await buildSummaryPdf(lang, entries, periodLabel);
  const stamp = new Date().toISOString().slice(0, 10);
  const filename = `kantu-resumen-${stamp}.pdf`;
  const file = new File([blob], filename, { type: 'application/pdf' });

  if (typeof navigator !== 'undefined' && navigator.share && navigator.canShare?.({ files: [file] })) {
    try {
      await navigator.share({ files: [file], title: 'Kantu', text: p('Resumen de salud generado por Kantu', 'Health summary generated by Kantu') });
      return 'shared';
    } catch (err) {
      if (err instanceof Error && err.name === 'AbortError') return 'cancelled';
      // fall through to plain download if sharing failed for another reason
    }
  }

  downloadFile(filename, blob, 'application/pdf');
  return 'downloaded';
}
